---
- name: Install MySQL
  hosts: mysql
  vars:
    ansible_python_interpreter: /usr/bin/python3 
  become: yes
  tasks:
    - name: Install MySQL Server
      apt: 
        name: mysql-server
        state: present

    - name: Start MySQL Server
      service:
        name: mysql
        state: started
        enabled: yes

- name: Add MySQL User
  hosts: mysql
  become: yes
  tasks:
    - name: Create Database User
      mysql_user:
        name: test
        password: test
        priv: '*.*:ALL'
        state: present