---
- name: Update apt
  hosts: mysql
  become: yes
  tasks:
    - name: APT Update
      apt:
        upgrade: yes
        update_cache: yes

- name: Make sure pymysql is present
  become: true # needed if the other tasks are not played as root
  tasks:
    - name: install mysql
      pip:
        name: pymysql
        state: present

- name: Install MySQL
  hosts: mysql
  vars:
    ansible_python_interpreter: /usr/bin/python3 
  become: yes
  tasks:
    - name: Install MySQL Server
      apt: 
        name: default-mysql-server
        state: present

    - name: Start MySQL Server
      service:
        name: mysql
        state: started
        enabled: yes

- name: Add MySQL User
  hosts: mysql
  become: yes
  tasks:
    - name: Create Database User
      mysql_user:
        name: test
        password: test
        priv: '*.*:ALL'
        state: present